In [ ]:
#Name:Sandhya Karki
#Un Id:2417743

In [2]:
#Importing the NumPy library.
import numpy as np

In [3]:
#Initialize an empty array with size 2X2.
empty_array = np.empty((2,2))
print("Empty array(2x2):")
print(empty_array)

Empty array(2x2):
[[4.71419307e-310 0.00000000e+000]
 [6.83858005e-310 6.83856618e-310]]


In [ ]:
#Initialize an all one array with size 4*2
ones_array =np.ones((4,2))
print("\nAll one array(4,2):")
print(ones_array)


All one array(4,2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Return a new array of given shape and type,filled with fill_value.
fill_value=6
filled_array = np.full((3,3), fill_value)
print("\nFilled array(3x3):")
print(filled_array)


Filled array(3x3):
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#Return a new array of zeros with shape and type as a given array.
given_array = np.array([[5,6],[7,8]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros array with same shape as given array:")
print(given_array)


Zeros array with same shape as given array:
[[5 6]
 [7 8]]


In [ ]:
#Return a new array of ones with same shape and type as a given array.
ones_like_array= np.ones_like(given_array)
print("\nones array with same shape as given array:")
print(ones_like_array)


ones array with same shape as given array:
[[1 1]
 [1 1]]


In [ ]:
#For an existing list new_list , convert to an numpy array.
new_list= [1,2,3,4]
new_array = np.array(new_list)
print("\nConverted Numpy array:")
print(new_array)


Converted Numpy array:
[1 2 3 4]


In [4]:
#Creating an array with values ranging from 1 to 49.
array = np.arange(10,49)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [5]:
#Creating 3*3 matrix with values ranging from 0 to 8.
x=np.arange(0,9).reshape(3,3)
print(x)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#Creating 3*3 identity matrix.
identity_matrix=np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#Creating random array of size 30.
array=np.random.random(30)
# finding the mean of array.
mean_value=np.mean(array)

print(array)
print("Mean value:",mean_value)

[0.28519448 0.01950785 0.5494783  0.10122015 0.41762584 0.27109996
 0.29766454 0.13806458 0.57541422 0.75825897 0.89613969 0.17285344
 0.14417436 0.39186239 0.77767353 0.96743652 0.75150233 0.20337742
 0.0633466  0.48562019 0.66298811 0.91704575 0.8064778  0.7117079
 0.92401857 0.21832599 0.21729824 0.23499618 0.9401014  0.52466793]
Mean value: 0.4808381073023696


In [8]:
#Creating a 10*10 array with random values.
random_array=np.random.random((10,10))
# Finding the minimum values and maximum values.
min_value=np.min(random_array)
max_value=np.max(random_array)
print(random_array)
print("Minimum value:",min_value)
print("Maximum value:",max_value)

[[0.16089205 0.36724579 0.09609009 0.48252165 0.34811143 0.75418259
  0.2309793  0.37602701 0.5014703  0.86974616]
 [0.62880456 0.82415179 0.13623885 0.47237088 0.97647657 0.70650896
  0.55438903 0.64041423 0.14284465 0.40262791]
 [0.71643527 0.13514439 0.4820732  0.47613358 0.14275795 0.2015927
  0.47941402 0.1916557  0.95584912 0.46290818]
 [0.06971754 0.92298779 0.22519372 0.92727224 0.20116531 0.08861163
  0.74954063 0.20077363 0.80159618 0.5671834 ]
 [0.31650072 0.78877862 0.77037141 0.0998389  0.63920822 0.83677864
  0.75790341 0.71166707 0.80044884 0.52116077]
 [0.78905853 0.07048131 0.88371481 0.6149114  0.42808629 0.44289017
  0.86028509 0.67119721 0.42789335 0.2624931 ]
 [0.60211736 0.11227415 0.43236708 0.18429711 0.24893381 0.27015282
  0.54423794 0.18500464 0.76605997 0.61538567]
 [0.96141648 0.06877312 0.55199535 0.71831816 0.45850636 0.36053637
  0.98722387 0.79421238 0.3170046  0.20963411]
 [0.99602504 0.883871   0.45791394 0.1449604  0.01149191 0.56401607
  0.19412983 

In [9]:
#Creating a zero array of size 10.
zero_array=np.zeros(10)
#Replacing fifth element with 1.
zero_array[4]=1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
# Reversing an array
array = np.array([1, 2, 0, 0, 4, 0])
reversed_array = array[::-1]
print(reversed_array)

[0 4 0 0 2 1]


In [11]:

array=np.ones((5,5))
#set the inner elements to 0
array[1:-1, 1:-1]=0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:

#Creating an 8** Numpy array filled with zeros and setting alternate elements to 1 to create a checkerboard pattern
array=np.zeros((8,8) ,dtype=int)
#Setting alternate rows starting from the second row with alternate columns to 1
array[1::2, ::2]=1
#Setting alternate rows starting from the first row with alternate columns to 1
array[::2, 1::2]=1
print(array)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [13]:

x=np.array([[1,2] ,[3,5] ])
y=np.array([[5,6] ,[7,8]])
v=np.array([9,10])
w=np.array([11,12])
#1.Add two array(x and y)
add=x+y
print("Add:", add)

#2.Subtract two array(x and y)
sub=x-y
print("\nSubtract:")
print(sub)

#3.Multiply the array y with any integer
multiply = y * 2
print("\nMultiplication of y with 2:")
print(multiply)

#4.Square of an each element in the array
square_x=x**2
square_y=y**2
square_v=v**2
square_w = w**2
print("\nSquare of x:")
print(square_x)
print("\nSquare of y:")
print(square_y)
print("\nSquare of v:")
print(square_v)
print("\nSquare of w:")
print(square_w)

#5.Dot product between v and w
dot_vw = np.dot(v,w)
print("\nDot product of v and w:")
print(dot_vw)

# Dot product between x and v
dot_xv=np.dot(x,v)
print("\nDot product of x and v:")
print(dot_xv)

#Dot product between x and y
dot_xy=np.dot(x,y)
print("\nDot product of x and y:")
print(dot_xy)

# 6.Concatenate:
#concatenate x and y along rows
concate_xy_rows = np.concatenate((x,y))
print("\nConcatenate x and y :")
print(concate_xy_rows)

#Concatenate v and w along columns
concate_vw_columns = np.concatenate((v,w))
print("\nConcatenate of v and w along columns:")
print(concate_vw_columns)

# 7.Concatenate x and v;
try:
    concate_xv =np.concatenate((x,v))
    print("\nConcatenate x and v:")
    print(concate_xv)
except ValueError as e:
  print("\nError while concatenating x and v:")
  print(e)

#Explanation of error:
print("\nExplanation: The shapes of x and v are incompatible for concatenation along rows.")
print("x has shape (2,2) and v has shape (2) so that we must reshape v to matc x's dimensions for successful concatenation")









Add: [[ 6  8]
 [10 13]]

Subtract:
[[-4 -4]
 [-4 -3]]

Multiplication of y with 2:
[[10 12]
 [14 16]]

Square of x:
[[ 1  4]
 [ 9 25]]

Square of y:
[[25 36]
 [49 64]]

Square of v:
[ 81 100]

Square of w:
[121 144]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenate x and y :
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate of v and w along columns:
[ 9 10 11 12]

Error while concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: The shapes of x and v are incompatible for concatenation along rows.
x has shape (2,2) and v has shape (2) so that we must reshape v to matc x's dimensions for successful concatenation


In [14]:

#Define the arrays A and B
A =np.array([[3,4], [7,8]])
B=np.array([[5,3], [2,1]])

# Prove A*A^(-1)=I
#Compute the inverse of A
A_inv =np.linalg.inv(A)
#Compute A * A^(-1)
A_product = np.dot(A,A_inv)
print("A * A^(-1) = I:")
print(A_product)

#2 .Prove AB != BA
#Compute AB
AB = np.dot(A,B)
#Compute BA
BA = np.dot(B,A)
print("\nAB:")
print(AB)
print("\nBA:")
print(BA)

#3. Prove (AB)^T =B^T *A^T
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T,A.T)
print("\n(AB)^T:")
print(AB_transpose)
print("\nB^T * A^T:")
print(BT_AT)

#Solve the system of linear equation using Inverse methods.
#Represent the equations in matrix form AX = B
A_linear = np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B_linear = np.array([-1,-3,9]).reshape(-1,1)

#Solve for x using inverse method
A_linear_inv = np.linalg.inv(A_linear)
X_solution = np.dot(A_linear_inv,B_linear)
print("\nSolution to the system of linear equations:")
print(X_solution)


A * A^(-1) = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Solution to the system of linear equations:
[[ 2.]
 [ 1.]
 [-2.]]


In [16]:
import time
import numpy as np

# 1. Element-wise Addition
size = 1_000_000

# Python Lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
start = time.time()
result_list_add = [list1[i] + list2[i] for i in range(size)]
time_list_add = time.time() - start

# Numpy Arrays
array1 = np.arange(size)
array2 = np.arange(size)
start = time.time()
result_array_add = array1 + array2
time_array_add = time.time() - start

# 2. Element-wise Multiplication

# Python Lists
start = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(size)]
time_list_mul = time.time() - start

# Numpy Arrays
start = time.time()
result_array_mul = array1 * array2
time_array_mul = time.time() - start

# 3. Dot Product

# Python Lists
start = time.time()
result_list_dot = sum(list1[i] * list2[i] for i in range(size))
time_list_dot = time.time() - start

# Numpy Arrays
start = time.time()
result_array_dot = np.dot(array1, array2)
time_array_dot = time.time() - start

# 4. Matrix Multiplication
matrix_size = 300  # Smaller size for Python lists
matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

# Python Lists - Matrix Multiplication
start = time.time()
result_matrix_mul = [
    [sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)]
    for i in range(matrix_size)
]
time_matrix_mul = time.time() - start

# NumPy Arrays - Matrix Multiplication
matrix_array1 = np.arange(1000**2).reshape(1000, 1000)
matrix_array2 = np.arange(1000**2).reshape(1000, 1000)
start = time.time()
result_array_matrix_mul = np.dot(matrix_array1, matrix_array2)
time_array_matrix_mul = time.time() - start

# Results
print(f"Element-wise Addition: Python Lists: {time_list_add:}s, NumPy Arrays: {time_array_add:}s")
print(f"Element-wise Multiplication: Python Lists: {time_list_mul:}s, NumPy Arrays: {time_array_mul:}s")
print(f"Dot Product: Python Lists: {time_list_dot:}s, NumPy Arrays: {time_array_dot:}s")
print(f"Matrix Multiplication: Python Lists (300x300): {time_matrix_mul:}s, NumPy Arrays (1000x1000): {time_array_matrix_mul:}s")


Element-wise Addition: Python Lists: 0.184828519821167s, NumPy Arrays: 0.004091739654541016s
Element-wise Multiplication: Python Lists: 0.1865382194519043s, NumPy Arrays: 0.0039920806884765625s
Dot Product: Python Lists: 0.16445326805114746s, NumPy Arrays: 0.0017726421356201172s
Matrix Multiplication: Python Lists (300x300): 6.11024808883667s, NumPy Arrays (1000x1000): 1.2118127346038818s
